### ISSUE TITLE
Doesn’t work anymore, flows useless!

### ISSUE THREAD

**Issue by JustThe2ofUs** [lvanderree/com.synplyworks.thenmore#14] opened 2019-04-21 00:01 UTC
Damn; it suddenly doesn’t work anymore. 
In every flow where the app was used: Broken. The variable of the app just got kicked out as it never existed before! 
Plus: When trying to choose a device while creating a new flow now - there’s no device to be found.... 
What’s wrong there? It’s realllly frustrating !!

**Comment by lvanderree** [comment] 2019-04-21 07:32
I guess it is a bug in Homey: 
https://athomcommunity.slack.com/conversation/C04SUGZ9E/p1555516692062000

> WeeJeWel   [Apr 17th at 5:58 PM]
> Workaround: `Homey.sessions.deleteSessions();` in https://developer.athom.com/tools/api-playground. 

Then restart the app


> WeeJeWel [5:57 PM]
> Fixed in the next release :slightly_smiling_face:

(after 2.1.1)

**Comment by JustThe2ofUs** [comment] 2019-04-21 10:32
Thx for answering so quick! ... though - the workaround doesn’t seem to work here. Cannot see any device to choose in the list of the app :(

**Comment by lvanderree** [comment] 2019-04-21 11:00
Hmmm, could you send me the Homey and App version you are using? And maybe send a diagnostic report from the settings of the app

**Comment by JustThe2ofUs** [comment] 2019-04-21 14:45
Hey and Happy Easter! 😊🥚
Sure - using the very latest versions on Homey and of the Homey-App as well. 
Diagnostics:
83175f92-0bca-4189-9504-7750db907de0

**Comment by lvanderree** [comment] 2019-04-24 08:53
From what I've seen, I guess that it is the same bug as described on slack.
Sorry to here the workaround did not help, but I would suggest to wait for the update that is talked about, since I cannot test anything myself, since I am not affected by this issue.

**Comment by lvanderree** [comment] 2019-04-24 08:54
Do you have this issue in a different browser (of incognito modus) as well?

**Comment by JustThe2ofUs** [comment] 2019-04-24 08:59
Hey there. 
I just tried now in safari and got the error message „unknown error occurred (session expired) when entering the „search“ field where usually selecting the devices or timers.

**Comment by lvanderree** [comment] 2019-04-24 09:05
looks like a duplicate of #13

**Comment by lvanderree** [comment] 2019-04-25 08:23
the beta of 2.1.2-rc3 should contain a fix for this issue

**Closed** 2019-11-04 19:19 UTC
