### ISSUE TITLE
works a few times, then doesn't

### ISSUE THREAD

**Issue by novaflash** [lvanderree/com.synplyworks.thenmore#11] opened 2019-03-20 18:27 UTC
yeah, i don't know why either. it works a few times, then at some point it just stops working and won't turn on anything anymore.

i go into the apps on homey, tell it to restart the timer app, then it works again for a couple of times. not sure what i can do to debug this or fix it.

i'm on version v0.4.3

**Comment by lvanderree** [comment] 2019-03-21 09:30
I think it is the same issue as in the homey 2 (0.7) versions:

There is something going on with the timeout methods not getting cleaned up properly I think. 


I noticed this warning in my logs:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect_error listeners added. Use emitter.setMaxListeners() to increase limit

I need to find some time to find the cause of this. However it will be difficult to fix this in 0.4 since my homey is running on 2.0

**Comment by novaflash** [comment] 2019-03-22 09:33
Maybe. Homey says my firmware version is:
homey_version | 1.5.13

**Comment by lvanderree** [comment] 2019-03-22 10:14
yeah that is what I guessed when you said you're running 0.4.3.

I can try to backport my fix (once I got it for 0.7/ homey 2.0), but I cannot test it.

**Comment by lvanderree** [comment] 2019-11-04 19:20
I am closing the issue, since this does not effect v0.7+ (or the homey2+ versions)

**Closed by lvanderree** 2019-11-04 19:20 UTC
